evergreen_financial_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("main.urls")),
    path('transactions/', include("transactions.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('category/', include('category.urls')),
    path('upload/', include('upload.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

main/urls.py
from django.urls import path

from .views import *

app_name = 'main'

urlpatterns = [
    path("", index, name="index"),
]

transactions/urls.py
from django.urls import path

from .views import *

app_name = 'transactions'

urlpatterns = [
    path('', TransactionListView.as_view(), name='transactions'),
    path('<int:pk>/update/', TransactionUpdateView.as_view(), name='edit_transaction'),
    path('<int:pk>/delete/', TransactionDeleteView.as_view(), name='delete_transaction'),
    
    # API's
    path('transactions_api/', TransactionListAPIView.as_view(), name='transactions_api'),
]

transactions/models.py
from django.db import models
from django.conf import settings
from category.models import Category

# Create your models here.
class Transaction(models.Model):
    date = models.DateField(null=True, blank=True)
    description = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    notes = models.TextField(max_length=500, null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.date} - {self.description} - {self.category} - ${self.amount} - {self.owner}"

transactions/forms.py
from django import forms
from .models import *

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = [
            "date",
            "description",
            "category",
            "notes",
            "amount"
        ]
        widgets = {
            'notes': forms.Textarea(attrs={'rows': 2, 'cols': 40}),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.order_by('name')

transactions/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.urls import reverse_lazy

# Django Views
from django.views.generic import TemplateView, View
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView


# Django Models
from django.db import models
from django.db.models import Sum, Min, Max
from .models import Transaction, Category
from django.db.models import Q, Sum, Count
from django.db.models.functions import TruncMonth


# Forms
from .forms import *

# Django Auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Misc
from django.utils import formats
from io import StringIO
from decimal import Decimal
from datetime import datetime
import csv

# Pagination
from .mixins import ViewPaginatorMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .pagination import CustomPageNumberPagination

# Serializers
from .serializers import TransactionSerializer

# Rest Framework
from rest_framework import generics, permissions, filters
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated




class TransactionListView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_list.html'
    model = Transaction
    context_object_name = 'transactions'
    
    
    
class TransactionUpdateView(LoginRequiredMixin, UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name_suffix = "_update"
    
    # Disable the date field and amount from user
    def get_form(self, form_class = None):
        form = super().get_form(form_class)
        form.fields['date'].disabled = True
        # form.fields['amount'].disabled = True
        return form
    
    def get_success_url(self):
        return reverse_lazy('transactions:transactions')
    
    
    
class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    template_name_suffix = "_delete"
    
    def get_success_url(self):
        return reverse_lazy('finance_tracker:transactions')



class TransactionListAPIView(generics.ListCreateAPIView):
    serializer_class = TransactionSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]
    pagination_class = CustomPageNumberPagination
    filter_backends = [filters.SearchFilter]
    search_fields = ['description', 'amount', 'date', 'category__name']
    
    def get_queryset(self):
        queryset = Transaction.objects.filter(owner=self.request.user)
        category = self.request.query_params.get('category')
        
        if category:
                queryset = queryset.filter(category__name=category)
                
        return queryset.order_by('-date')
    
    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        total_transactions = queryset.count()
        total_amount = queryset.aggregate(Sum('amount'))['amount__sum'] or 0
        min_date = queryset.aggregate(Min('date'))
        max_date = queryset.aggregate(Max('date'))
        
        categories = Transaction.objects.filter(
            owner=request.user).values_list(
                'category__name', flat=True).distinct().order_by('category__name')
        
        formatted_min_date = min_date['date__min'].strftime("%b %d, %Y") if 'date__min' in min_date and min_date['date__min'] else 'N/A'
        formatted_max_date = max_date['date__max'].strftime("%b %d, %Y") if 'date__max' in max_date and max_date['date__max'] else 'N/A'

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            response_data = {
                'next': self.paginator.get_next_link(),
                'previous': self.paginator.get_previous_link(),
                'current_page': self.paginator.page.number,
                'total_pages': self.paginator.page.paginator.num_pages,
                'categories': categories,
                'stats': {
                    'min_date': formatted_min_date,
                    'max_date': formatted_max_date,
                    'total_transactions': total_transactions,
                    'total_amount': total_amount,
                },
                'results': serializer.data
            }
            return Response(response_data)

        serializer = self.get_serializer(queryset, many=True)
        response_data = {
            'stats': {
                'min_date': formatted_min_date,
                'max_date': formatted_max_date,
                'total_transactions': total_transactions,
                'total_amount': total_amount,  
            },
            'results': serializer.data,
        }
        return Response(response_data)


    def perform_create(self, serializer):
        """Override to set the owner of the transaction to the current user."""
        serializer.save(owner=self.request.user)

transactions/templates/transactions/transaction_delete.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% load static %} 

{% block content %}

   <div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow p-4 border-danger"> 
                <div class="card-header bg-danger text-white text-center">
                    <i class="bi bi-trash-fill me-2"></i> Confirm Delete
                </div>
                <div class="card-body text-center">
                    <h2 class="card-title mb-4">Are you sure you want to delete this?</h2>

                    {% if object %}
                    <p class="card-text mb-3">
                        You are about to delete the following item:
                    </p>
                    <ul class="list-unstyled mb-3">
                        <li><strong>Date:</strong> {{ object.date|default:"N/A" }}</li>
                        <li><strong>Description:</strong> {{ object.description|default:"N/A" }}</li>
                        <li><strong>Category:</strong> {{ object.category|default:"N/A" }}</li>
                        <li><strong>Amount:</strong> {{ object.amount|default:"N/A" }}</li>
                    </ul>
                    {% endif %}

                    <p class="card-text mb-4">This action cannot be undone.</p> 

                    <form method="post">
                        {% csrf_token %}
                        <div class="d-grid gap-2 d-md-block">
                            <button type="submit" class="btn btn-danger me-2">Confirm Delete</button>
                            <a href="{% url 'transactions:transactions' %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

transactions/templates/transactions/transaction_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static "transactions/css/main.css" %}">
{% endblock extra_css %}

{% block content %}
<div>
    <div class="container container-transactions-page min-vh-100 mb-3">
        <div class="d-flex row m-2">
            <div class="col mt-3">
                <h2 class="fw-bold primary-text">Transactions</h2>
            </div>
        </div>
        
        {% comment %}------ Stats Bar ------{% endcomment %}
        <div class="row flex-wrap justify-content-center mx-2 gap-3 row-cols-sm-1 row-cols-lg-4">

            <div class="db-card flex-grow-1 card shadow-sm border-0 rounded-3">
                <div class="card-body data p-4 d-flex flex-column align-items-center justify-content-center">
                    <p class="fw-light text-muted text-uppercase mb-1">Transactions</p>
                    <h5 class="fw-bold mb-0">
                        <div class="loader-div spinner-for-stat" style="display: none;">
                            <div class="loader"></div>
                        </div>
                        <span class="stat-data" id="transaction-count-display"></span>
                    </div>
                </h5>
            </div>
        
        
            <div class="db-card card flex-grow-1 shadow-sm border-0  rounded-3">
                <div class="card-body data p-4 d-flex flex-column align-items-center justify-content-center">
                    <p class="fw-light text-muted text-uppercase mb-1">Date Range</p>
                    <h5 class="fw-bold mb-0">
                        <div class="loader-div spinner-for-stat" style="display: none;">
                            <div class="loader"></div>
                        </div>
                        <span class="stat-data" id="date-range-display"></span>
                    </h5>
                </div>
            </div>
            
            <div class="db-card card flex-grow-1 shadow-sm border-0  rounded-3">
                <div class="card-body data p-4 d-flex flex-column align-items-center justify-content-center">
                    <p class="fw-light text-muted text-uppercase mb-1">Total</p>
                    <h5 class="fw-bold mb-0">
                        <div class="loader-div spinner-for-stat" style="display: none;">
                            <div class="loader"></div>
                        </div>
                        <span class="stat-data" id="stats-total-display"></span>
                    </h5>
                </div>
            </div>
        </div>
        
        <div class="row justify-content-between mt-4">
            {% comment %}------ Search Field ------{% endcomment %}
            <div class="col-lg-3 col-md-6 col-sm-12 align-self-end">
                <form method="get">
                    <div class="input-group" style="--search-icon-url: url({% static 'transactions/images/search.svg' %});">
                        <input id="search-bar"type="text" class="form-control transaction-search-field" placeholder="Search transactions..." name="search_term" transaction-search-bar/>
                    </div>
                </form>
            </div>
            {% comment %}------ Category Filter Menu ------{% endcomment %}
            <div class="col-lg-2 col-md-3 col-sm-12">
                <div class="dropdown filter-badge open">
                    <a
                    class="btn btn-sm text-light dropdown-toggle"
                    type="button"
                    id="filter-badge"
                    data-bs-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >
                    Category Filter
                </a>
                <div class="dropdown-menu filter-dropdown-menu" aria-labelledby="triggerId"></div>
            </div>
            
            <div class="col">
                <span class="btn btn-sm clear-filter-btn hidden w-100"><i class="bi bi-x-lg"></i> Clear Filter</span>
            </div>
        </div>
    </div> 
    
    <div class="loader-div spinner-for-table" style="display: none;">
        <div class="loader"></div>
    </div>

    {% comment %}------ Transaction Table ------{% endcomment %}
    <div id="transaction-table" class="data table-responsive mt-2">
        <table class="table table-hover" style="width: 100%;">
            <thead>
                <tr>
                    <th scope="col" class="date-col">Date</th>
                    <th scope="col" class="hide-description-col">Description</th>
                    <th scope="col" class="">Category</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody class="table-group-divider table align-middle" transaction-row-container></tbody>
        </table>
        
    </div> 
    
    
    {% comment %}------ Pagination ------{% endcomment %}
    <div class="text-center pagination-div">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                <li class="page-item previous-page disabled">
                    <a class="page-link previousUrl" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo; Previous</span>
                    </a>
                </li>
                <li class="page-item active " aria-current="page">
                    <a class="page-link current-page" href="#"></a>
                </li>
                <li class="page-item next-page disabled">
                    <a class="page-link nextUrl" href="#" aria-label="Next">
                        <span aria-hidden="true">Next &raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    
</div>



{% comment %}------ Filter Btn ------{% endcomment %}
<template filterButtonTemplate>
    <a class="dropdown-item category-filter-badge"></a>
</template>

{% comment %}------ Transaction List Table ------{% endcomment %}
<template transaction-row-template>
    <tr>
        <td class="transaction-date date-col">
            <span class="desktop-date" transaction-desktop-date></span> 
            <span class="mobile-date" transaction-mobile-date></span>
        </td>
        <td class="transaction-description hide-description-col" transaction-description></td>
        <td class="transaction-category"><span id="category-pill" class="badge badge-pill category-badge text-light category-col" transaction-category></span></td>
        <td transaction-amount></td>
        <td class="transaction-action">
            <a href="#" data-edit-url="{% url 'transactions:edit_transaction' pk='0' %}">
                <i class="bi bi-pencil-square edit-link"></i>
            </a> |
            <a href="#" data-delete-url="{% url 'transactions:delete_transaction' pk='0' %}">
                <i class="bi bi-trash3-fill text-secondary delete-link"></i>
            </a>
        </td>
    </tr>
</template>
{% endblock %}

{% block extra_js %}
<script type="module" src="{% static 'transactions/js/main.js' %}"></script>
{% endblock %}

transactions/templates/transactions/transaction_update.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% load static %} 

{% block content %}
    <div id="update-container" class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow p-4">
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Update Transaction</h2>
                        <form method="post">
                            <div>
                                {% csrf_token %}
                                {% crispy form %}
                                <div class="text-center mt-3">
                                    <button type="submit" class="btn btn-dark btn-block">Update Transaction</button>
                                    <a href="{% url 'transactions:transactions' %}" class="btn btn-secondary">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
{% endblock content %}